name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout hidden tests
        uses: actions/checkout@v4
        with:
          repository: provaac/ex1-tests     # owner/repo exactes
          ref: main                         # canvia-ho si la branca no és main
          path: .hidden-tests
          token: ${{ secrets.CLASSROOM_PAT }}
          persist-credentials: false
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
