name: GitHub Classroom Autograder

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout hidden tests (provaac/solver_ex1)
        uses: actions/checkout@v4
        with:
          repository: provaac/solver_ex1
          ref: main
          path: .hidden-tests
          token: ${{ secrets.CLASSROOM_PAT }}
          persist-credentials: false
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Debug: list hidden tests dir
        run: |
          echo "Files under .hidden-tests (maxdepth 4):"
          find .hidden-tests -maxdepth 4 -type f | sort || true

      - name: Autograding
        uses: education/autograding@v1
