name: CI - ex1

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout student repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate dataset (si cal)
        run: |
          python tools/make_dataset.py || true

      # === CHECKOUT REPO AMB EL TEST OCULT ===
      - name: Checkout hidden tests repo
        if: ${{ secrets.HIDDEN_TESTS_TOKEN != '' }}
        uses: actions/checkout@v4
        with:
          repository: your-org/solver_ex1        # ⬅️ canvia-ho al teu repo amb test_hidden.py
          token: ${{ secrets.HIDDEN_TESTS_TOKEN }}
          path: hidden
          fetch-depth: 1
          persist-credentials: false

      # === EXECUTA ELS TESTS OCULTS (i públics si vols) ===
      - name: Run pytest (hidden + public)
        run: |
          # Públics (si en tens al template)
          if [ -d tests ]; then
            pytest -q tests || exit 1
          fi
          # Ocults (des del repo clonat)
          if [ -f hidden/tests/test_hidden.py ]; then
            pytest -q hidden/tests/test_hidden.py
          fi
